### ISSUE TITLE
能否增加 TSPDT top1000 榜单

### ISSUE THREAD

**Issue by xoyabc** [bimzcy/rank4douban#2]
官网地址：

http://www.theyshootpictures.com/gf1000_all1000films.htm

```
TSPDT全称为“THEY SHOOT PICTURES, DON'T THEY?”，是一个网站和数据库； 其主要的数据来源有两

个（每年更新一次，按照去年的数据，选票数每年都会变化） 一是5495张影评人和电影学者的私人投

票 二是3302张各类综合榜单 对总共8797张榜单进行加权计算，就可以给所有引用的电影排一个名

次；同理，导演也可以排一个名次 每年tspdt官方都会刷新电影及导演排名，对于排名前250位的导

演，被认为是“载入世界电影史的优秀导演”；对于排名前1000名的电影，被认为是“载入世界电影史的

优秀电影” 总之，tspdt榜单排名，基本可以看做电影及导演业内地位的象征。
```

**Comment by Rhilip** [comment]
请参照 `/data` 目录文件样式，提交csv格式的数据。我会pr的

**Comment by BruceLee569** [comment]
@xoyabc @Rhilip 

我用python爬下来了，有几部在豆瓣查不到，TSPDT有两个榜单，一个是 [总榜](http://www.theyshootpictures.com/gf1000_all1000films_table.php)，一个是 [21世纪榜](http://www.theyshootpictures.com/21stcentury_allfilms_table.php)，我爬的是总榜，榜单的具体情况可以看看 [榜单导读](http://www.theyshootpictures.com/21stcentury.htm)

**Comment by Rhilip** [comment]
@BruceLee569 相关pr已经合并，json文件会在下次自动构建时候生成。本issue结束

**Comment by xoyabc** [comment]
@BruceLee569  
多谢。 方便的话可否提交PR至 update_snippets.py，后面让自动更新下。

**Comment by xoyabc** [comment]
`有几部在豆瓣查不到`

@BruceLee569   这几部没找到的已更新，麻烦PR，感谢。

[07_tspdt_top_1000.csv](https://github.com/bimzcy/rank4douban/blob/master/data/07_tspdt_top_1000.csv)

```shell
rank
236
492
503
671
734
838
989
1000
```

**Comment by xoyabc** [comment]
@BruceLee569   我根据 `dbid` 请求豆瓣，之后对比了影片年份和导演，发现以下影片的 `dbid` 有误，已提交，麻烦 PR，感谢。

```shell
rank
444
481
527
557
613
715
827
874
879
889
```
